before_install:
  - >-
    openssl aes-256-cbc 
    -K $encrypted_5bf7eab0acce_key 
    -iv $encrypted_5bf7eab0acce_iv 
    -in github_deploy_key.enc 
    -out github_deploy_key 
    -d
  - chmod 600 github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add github_deploy_key
